In [2]:
import numpy as np

def svd(matrix):
  # Step 1: Calculate the covariance matrix
  covariance_matrix = np.dot(matrix.T, matrix)

  # Step 2: Find the eigenvalues and eigenvectors of the covariance matrix
  eigenvalues, eigenvectors = np.linalg.eig(covariance_matrix)

  # Step 3: Sort the eigenvalues and eigenvectors in descending order of eigenvalue magnitude
  sorted_indices = np.argsort(eigenvalues)[::-1]
  eigenvalues = eigenvalues[sorted_indices]
  eigenvectors = eigenvectors[:, sorted_indices]

  # Step 4: Calculate the singular values (sqrt of eigenvalues)
  singular_values = np.sqrt(eigenvalues)

  # Step 5: Create the diagonal matrix of singular values
  sigma = np.diag(singular_values)

  # Step 6: Construct the left singular matrix (normalized eigenvectors)
  u = np.dot(matrix, eigenvectors) / singular_values

  # Step 7: Calculate the conjugate transpose of the right singular matrix
  vh = eigenvectors.T

  return u, sigma, vh

# Example usage
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

u, sigma, vh = svd(matrix)

# Print the original data
print("Original data:")
print(matrix)

# Print the transformed data
transformed_data = np.dot(u, np.dot(sigma, vh))
print("Transformed data:")
print(transformed_data)

Original data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transformed data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
